trigger:
  - master

pool:
  image: ubuntu-latest
steps:
  - checkout: self
    submodules: true
  - script: |
      rm *.py
      rm *.sh
      rm *.lock
      rm *.toml
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      azure_static_web_apps_api_token: $(deployment_token)